import MessageActionBtnsComponent
    from "@components/messengerLayout/messengerLayoutContent/messageActionContainer/messageActionBtns/MessageActionBtnsComponent";

export default MessageActionBtnsComponent